### ISSUE TITLE
create a fallback for an unpublished pages.

### ISSUE THREAD

**Issue by hagcin** [boundaryfunctions/PagePathHistoryManager#2]
It's helpful to have unpublished content instead of deleting it. Just to have a record of that page, without moving it to the trash where it could be lost forever. If you unpublish content you can not create a redirect for that content because the page already exists. 

"'The requested path is already in use by another page.'"

**Comment by bfncs** [comment]
Thanks for reporting, your problem should be pretty common. The most straightforward solution here would be to check only if the currently used path is used by a published page (or not checking for existing pages using this path at all). I'm going to implement this in the next days.
