### ISSUE TITLE
Confirm it PW 3.х compatible and post to modules directory

### ISSUE THREAD

**Issue by ivangretsky** [boundaryfunctions/PagePathHistoryManager#3]
Hey! This is a useful module. PW is officially ver. 3 now, so it is right time to upgrade the modules to be compatible (or just check for compatibility).

And I did not find in modules directory. Are there reasons it is not there?

**Comment by bfncs** [comment]
Hi @ivangretsky! I'm afraid nowadays I don't work with PW any more. Therefore I will probably not be able to test this module with version 3 and update it accordingly. Please feel free to fork and maintain this module.
